// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using final.Data;

#nullable disable

namespace final.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20251127000143_UpdateProductSeeds")]
    partial class UpdateProductSeeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("final.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Lname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mname")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("CustomerId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("final.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("final.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("final.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Inventory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Category = "Dessert",
                            Inventory = 10,
                            Name = "Cherry Toast with Cream cheese",
                            Price = 7m
                        },
                        new
                        {
                            ProductId = 2,
                            Category = "Dessert",
                            Inventory = 10,
                            Name = "Jelly Cat",
                            Price = 7m
                        },
                        new
                        {
                            ProductId = 3,
                            Category = "Dessert",
                            Inventory = 10,
                            Name = "Lemon and Blueberry Cheesecake",
                            Price = 8m
                        },
                        new
                        {
                            ProductId = 4,
                            Category = "Dessert",
                            Inventory = 10,
                            Name = "Orange Cat",
                            Price = 2m
                        },
                        new
                        {
                            ProductId = 5,
                            Category = "Dessert",
                            Inventory = 10,
                            Name = "Raspberry Macaroon",
                            Price = 2m
                        },
                        new
                        {
                            ProductId = 6,
                            Category = "Dessert",
                            Inventory = 10,
                            Name = "Ube Macaroon",
                            Price = 2m
                        },
                        new
                        {
                            ProductId = 7,
                            Category = "Drink",
                            Inventory = 10,
                            Name = "Blue Milk tea",
                            Price = 6m
                        },
                        new
                        {
                            ProductId = 8,
                            Category = "Drink",
                            Inventory = 10,
                            Name = "Coffee",
                            Price = 6m
                        },
                        new
                        {
                            ProductId = 9,
                            Category = "Drink",
                            Inventory = 10,
                            Name = "Strawberry Milk",
                            Price = 6m
                        },
                        new
                        {
                            ProductId = 10,
                            Category = "Cake",
                            Inventory = 10,
                            Name = "Chery Burnt-Basque Cheesecake",
                            Price = 30m
                        },
                        new
                        {
                            ProductId = 11,
                            Category = "Cake",
                            Inventory = 10,
                            Name = "Marshmello Cake",
                            Price = 20m
                        },
                        new
                        {
                            ProductId = 12,
                            Category = "Cake",
                            Inventory = 10,
                            Name = "Mouse Cake",
                            Price = 25m
                        },
                        new
                        {
                            ProductId = 13,
                            Category = "Cake",
                            Inventory = 10,
                            Name = "Ratatouille Cake",
                            Price = 22m
                        });
                });

            modelBuilder.Entity("final.Models.Order", b =>
                {
                    b.HasOne("final.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("final.Models.OrderItem", b =>
                {
                    b.HasOne("final.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("final.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("final.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("final.Models.Product", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
