// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using final.Data;

#nullable disable

namespace final.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20251111023112_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("final.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Lname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mname")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("CustomerId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("final.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("final.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Inventory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Category = "Plushies",
                            Inventory = 10,
                            Name = "Tom Plushie",
                            Price = 30m
                        },
                        new
                        {
                            ProductId = 2,
                            Category = "Plushies",
                            Inventory = 10,
                            Name = "Jerry Plushie",
                            Price = 30m
                        },
                        new
                        {
                            ProductId = 3,
                            Category = "Plushies",
                            Inventory = 10,
                            Name = "Nibble Plushie",
                            Price = 25m
                        },
                        new
                        {
                            ProductId = 4,
                            Category = "Figurines",
                            Inventory = 10,
                            Name = "Tom Figurine",
                            Price = 40m
                        },
                        new
                        {
                            ProductId = 5,
                            Category = "Figurines",
                            Inventory = 10,
                            Name = "Jerry Figurine",
                            Price = 40m
                        },
                        new
                        {
                            ProductId = 6,
                            Category = "Figurines",
                            Inventory = 10,
                            Name = "Nibble Figurine",
                            Price = 35m
                        },
                        new
                        {
                            ProductId = 7,
                            Category = "Figurines",
                            Inventory = 10,
                            Name = "Spike Figurine",
                            Price = 30m
                        },
                        new
                        {
                            ProductId = 8,
                            Category = "Poster",
                            Inventory = 10,
                            Name = "Tom and Jerry Poster no.1",
                            Price = 15m
                        },
                        new
                        {
                            ProductId = 9,
                            Category = "Poster",
                            Inventory = 10,
                            Name = "Tom and Jerry Poster no.2",
                            Price = 15m
                        },
                        new
                        {
                            ProductId = 10,
                            Category = "Poster",
                            Inventory = 10,
                            Name = "Tom and Jerry Poster no.3",
                            Price = 15m
                        });
                });

            modelBuilder.Entity("final.Models.Order", b =>
                {
                    b.HasOne("final.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("final.Models.Product", "Product")
                        .WithMany("Orders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("final.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("final.Models.Product", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
